### PR TITLE
IP2V - Image Prompt 2 Video Via VLM

### PR DESCRIPTION
**Pull request by Dango233**
# Experimental IP2V - Image Prompting to Video via VLM by @Dango233

NOTE: Minimum 20GB Vram required (VLM qualtization not implemented yet)

Now you can feed image to the VLM as condition of generations! This is different from image2video where the image become the first frame of the video. IP2V uses image as a part of the prompt, to extract the concept and style of the image.
So - very much like IPAdapter - but VLM will do the heavy lifting for you!

Now this is a tuning free approach but with further task specific tuning we can expand the use scenarios.

### CODE REVIEW

**Comment by Dango233** [comment]
This modifies the base nodes quite a bit - Although it has no impact on the base t2i generation for now but I feel it needs more attention from you before open for merging @kijai

**Comment by kijai** [comment]
Interesting idea, do you have any examples? I can't seem to get it to work, tried on both my Windows and Linux installs and it simply exits when it starts to encode. On Windows the LVM loading also took forever for some reason, on Linux that was fast but still just crashes.

**Comment by selectai255** [comment]
hi i havn't tried this yet but can you tell me how it differs from feeding an image to qwen2 with instructions to create a prompt , i can do this with 16gb but your method says it needs 20gb 
thanks

**Comment by kijai** [comment]
From the couple of runs I tried right now, this feels very similar to using another model to make you the prompt, however this would remove the need to load yet another as the same model can do text/img, in that sense it's better.

I don't think it should replace the default text encode node though and it should be it's own separate node, changing nodes this much would force people to remake them in old workflows and cause some confusion.

**Comment by Dango233** [comment]
With direct image embedding passing into the model the image model should be more articulative than using a vlm to bridge

**Comment by Dango233** [comment]
> From the couple of runs I tried right now, this feels very similar to using another model to make you the prompt, however this would remove the need to load yet another as the same model can do text/img, in that sense it's better.
> 
> I don't think it should replace the default text encode node though and it should be it's own separate node, changing nodes this much would force people to remake them in old workflows and cause some confusion.

Yeah, I kinda feel the same way - How about I separate this into another encode/loader node pair?

**Comment by Dango233** [comment]
> From a couple of runs I tried right now, this feels very similar to using another model to make you the prompt. However, this would remove the need to load yet another as the same model can do text/img; in that sense, it's better.

With default ::4 yes - but if you crank this up to like ::2, it would be able to capture details that will be missing from the text proxy.
Well, on the other hand, it's harder to remove the unwanted part, tho.

**Comment by kijai** [comment]
> > From the couple of runs I tried right now, this feels very similar to using another model to make you the prompt, however this would remove the need to load yet another as the same model can do text/img, in that sense it's better.
> > I don't think it should replace the default text encode node though and it should be it's own separate node, changing nodes this much would force people to remake them in old workflows and cause some confusion.
> 
> Yeah, I kinda feel the same way - How about I separate this into another encode/loader node pair?

Yeah I'd say that's necessary as I always get tons of issue reports from simply changing one widget :sweat_smile:

**Comment by selectai255** [comment]
> From the couple of runs I tried right now, this feels very similar to using another model to make you the prompt, however this would remove the need to load yet another as the same model can do text/img, in that sense it's better.
> 
> I don't think it should replace the default text encode node though and it should be it's own separate node, changing nodes this much would force people to remake them in old workflows and cause some confusion.

ok thanks for reply anything better is good , i hope it can be made to run in 16gb or less

**Comment by Dango233** [comment]
@kijai OK seperate node now!

**Comment by fblissjr** [comment]
> With direct image embedding passing into the model the image model should be more articulative than using a vlm to bridge

fwiw this makes sense to me and was tangential to an experimental path i was going down myself.

was trying to use this same model (w/o the vision tower removed), but with the embeddings passed in, captured, and then see if it's possible to do representation engineering / control vector'ing on it for.. more control over a specific output. 

my guess is the control vector probably breaks more things than it helps, but i'm compelled to try it.

either way - i think this approach is sound, and should be optimized in experimental mode (for now). if the vision tower embeddings line up to the original source image, then theres a path.

**Comment by fblissjr** [comment]
@Dango233 on a separate note, is the vision tower just used at the start, or throughout each step?

**Comment by Dango233** [comment]
> @Dango233 on a separate note, is the vision tower just used at the start, or throughout each step?

Only at the start - then hidden\_state goes into conditioning as usual.

Might be interesting if somehow it can form a loop in the sampling process.....

**Comment by zer0int** [comment]
I don't know how / if this could be meaningfully applied to HunyuanVideo, so I'm just gonna drop this here as "some ideas" / observations.

1. CLIP 'opinion' about image. Encode image, use gradient ascent on text embeddings, optimize for cosine similarity.
2. Use created text embeddings for model inversion -> use CLIP's ViT to create image. Pretty strange "silent mail ping-pong" between encoders, but an interesting insight into CLIP and how complex its representations are.

 clip-image-feature
 
 There is a thing called LLM2CLIP: [https://github.com/microsoft/LLM2CLIP](https://github.com/microsoft/LLM2CLIP)

**Pull request merged**
